### ISSUE TITLE
Prefabs and assets missing

### ISSUE THREAD

**Issue by 0risin** [HelloKitty/Booma.PSOBB.Client#1]
Besides the opening screen, no scene has its prefabs or scripts.

As I understand this is going to become a full fledged , open source, PSO:BB client. We should concentrate on rebuilding/ripping and implementing PSO assets. Then go on to building the scenes and functionality.
Given the networking works, new assets can be created and swapped with old ones.

Firstly I'd like to inspect the scenes that were created so far.

With the animations and models from the original clients, I could recreate the combat system since I have a few weeks off.

**Comment by HelloKitty** [comment]
Oh yes sorry, I should have mentioned that. Only the title and login screen exist in the client provided here. The .scene files you see are just left over from the stripping down of the old client.

Eventually more content and scenes will come back when needed. Not anytime soon though.

**Comment by HelloKitty** [comment]
Also we are only implementing packets and their handlers right now. Nothing related to actual gameplay is being worked on. The main work is in the Booma.Proxy repo. I wouldn't expect too much from this repo, nor will there be much visual or art/content related work done soon.

Expect cubes and floor meshes for awhile!

**Comment by 0risin** [comment]
You're doing great work!

I think it's still a worthwhile endeavour to collect the PSO:BB assets and make them available. I'm not a networking developer but I can't imagine thats the only front that CAN be tackeled at this time.

Honestly I didn't contribute to the project so far at all, because the project hasn't lifted off far from the networking stage. I've watched since the inception or rather since I contacted you regarding my own remake project.
Thats was multiple years ago. There is no doubt that you and the rest of the team is very talented, focused and perfectionist at their craft. But changing the projects direction every few months won't incentivise people to contribute.

Visual representation is important and I'd like to get involed in the project to get that other fronts started. I'm talking characters, enemies, combat, doors opening, what have you. That only works with good communication with you engineers. I'd suggest a discord channel (it's free).

Summerize:
I'm not be a network engineer. 
I am a developer and worked a lot in unity implementing and studying character and combat systems from games. Also general (Level and Game)-Design.
The project needs to start on multiple fronts besides networking to incentivise contributions from artists, programmers and general PSO-System-Experts and I'd like to have a hand in that. That requires good communication, I'd suggest a discord channel (it's free).

**Comment by HelloKitty** [comment]
It's difficult to design any other systems without first exploring and understanding the PSOBB networking. Which I'm still doing. I'm sure it doesn't play a trivial role in many things so I'm unsure yet what can be worked on other than implementing DTOs for the packets.

If you're interested in assets then Kion's old work, which isn't public but there are some old uploads, will allow you to extract many assets. https://github.com/bogglez/Ninja-Lib . However, many of the original assets are not usable for various reasons. Either way the underlying systems that would drive this art/assets can be created and worked on using cubes. I think I'm going to avoid doing anything visual for abit and see what results.

I wouldn't say we changed direction every few months. There are some major design changes over the year. All in an effort to sustain longterm collaberation. Always a WIP. This is the only direction change I think we've ever had.

So for now it's just implementing packets and dealing with networking, nothing else I think can really be worked on without the risk of it being incompatible with what needs to be built networking-wise.

**Comment by 0risin** [comment]
I suppose you don't need actual contribution from in a department you aren't comfortable in.
Either you want to stay in control or there is another issue. This is definitely a hinderence to the project. 

I am comfortable saying that because I described this issue some of my project leading friends I worked with in IT. They agreed that keeping a game in network development is basically non-sensical.
It is important, yes but not the only deciding factor. As you know game consists of game mechanics and art.

Maybe you just don't know how to use your Network API for an action MMO. Then you still shouldn't promote your WIP API as a love product towards PSO.

I ask you to rethink YOUR decision not to work on anything but networking. Or at least run it by your cooperating colleges.

**Comment by HelloKitty** [comment]
Right now I'm working on login packets/payloads. Not sure what to say. There are some hints of accusations of afew things in your response. Anywhere from accusing me of hindering the project, mismanagement and poor leadership, being misleading about the networking in some fashion which is not my design or API but instead Sega's protocol from 2005. There is a lot here, and I'm just going to respond it as I have througout this thread.

@SnipeOrigin over the years I've become comfortable in a handful of the departments involved in game development. Control is obviously not something at the forefront of my mind, since the entire project is essentially built upon the original Sega protocol and network design, but that's the thing. I'm not yet familiar with its entirety and knowing that information could drastically change how certain features client-side should be developed.

If you want to work on something you're welcome to work on it. I just have no idea what will happen. I have no idea if what will be created will conflict with how Sega did something or how it would need to be done. I just don't have information on the sort of features you're talking about right now. Such as combat. It's not a simple feature and will require knowledge of how PSOBB networks it.

I just spoke to Soly and creating combat won't work unless you take into consideration that one of the client's hosts the simulation and seems to relay the events to other party members.

You can work on what you want. I can't promise that it will be compatible with the networking once we get to the point though.

In end only current other contributor to this custom PSOBB project Soly, the person who has been working with me to make this a reality, doesn't have a strong opinion on the current direction but is satisfied with the progress and thinks generally the project is going in the right direction. Mostly because he, like many future others I hope, is able to contribute utilizing his experience and domain specific knowledge on PSO reverse engineering.

So I do not plan to shift anything. Nor do I think I've said anything conflicting with these statements in the recent video asking for people with PSO protocol, domain specific knowledge or reverse engineering skills to come contribute to implement the networking. That's the only current goal right now.

**Comment by 0risin** [comment]
Thank you that cleared everything up.
